styles/scss/placeholders/_visually-hidden.scss
https://www.w3.org/WAI/tutorials/forms/labels/#hiding-the-label-element
=> Added visually hidden placeholder.

.gitattributes, CHANGELOG.md
Added files that will not be pulled when installing the script using npm.
=> Add gitattributes file

CHANGELOG.md, blocks/init/custom/divider/components/divider-editor.js, blocks/init/custom/divider/components/divider-options.js, blocks/init/custom/divider/divider-block.js, blocks/init/custom/divider/divider-style.scss, blocks/init/custom/divider/divider.php, blocks/init/custom/divider/docs/readme.md, blocks/init/custom/divider/docs/story.js, blocks/init/custom/divider/manifest.json, blocks/init/custom/jumbotron/components/jumbotron-editor.js
=> added new divider block

CHANGELOG.md, styles/scss/placeholders/_absolute-center.scss
Changelog
---
* Added placeholder `absolute-center` for absolutely positioning an element.
=> Added absolute-center placeholder

setup/create-wp-project/package.json, setup/create-wp-project/src/blocks.js
Changelog
---
* Modified setup script to accomodate #70
=> Expect blocks to be 1 level lower

CHANGELOG.md, setup/create-wp-project/package.json, setup/create-wp-project/src/arguments.js, setup/create-wp-project/src/blocks.js, setup/create-wp-project/src/commands/plugin.js, setup/create-wp-project/src/commands/theme.js
Changelog
---
* Added header & footer to setup script block copy process
=> Copy header and footer

CHANGELOG.md, scripts/register-block.js
Added foreground icon color option that can be pulled from global manifest
=> Add foreground icon color

CHANGELOG.md, blocks/init/src/blocks/components/header/header-style.scss, blocks/init/src/blocks/components/menu/components/horizontal/menu-horizontal-style.scss, blocks/init/src/blocks/components/menu/components/vertical/menu-vertical-style.scss, blocks/init/src/blocks/components/menu/menu.php
Changelog
---
- Removed hardcoded media-specific display properties
- Added 2 possible modifiers to menu for media-specific display property
=> Add media blender modifiers to menu component

blocks/init/src/blocks/components/scroll-to-top/assets/index.js, blocks/init/src/blocks/custom/carousel/assets/carousel-slider.js, blocks/init/src/blocks/custom/carousel/assets/index.js
- removed jQuery from scroll to top component
- removed jQuery from carousel slider
- changed Carousel slider swiper initialization
=> Remove jquery

CHANGELOG.md, setup/create-wp-project/package.json, setup/create-wp-project/src/blocks.js
Changelog
---
- Added copying of components used by header & footer
=> Setup script for components

CHANGELOG.md, blocks/init/src/blocks/custom/example/components/example-editor.js, blocks/init/src/blocks/custom/example/components/example-options.js, setup/create-wp-project/package.json, setup/create-wp-project/src/basics/console.js, setup/create-wp-project/src/commands/plugin.js, setup/create-wp-project/src/commands/theme.js, setup/create-wp-project/src/search-replace.js, setup/create-wp-project/src/storybook.js
Fixed
---
* Closed #116 
* Closed #96 
* Intro acsi-art now breaks into 2 lines (now doesn't look jumbled on narrow terminals)
=> Fixing boilerplate setup

CHANGELOG.md, styles/scss/mixins/_all.scss, styles/scss/mixins/_font-face.scss
Add font-face mixin for generating `@font-face` definition
Add annotation for sassdoc
Add changelog
=> font-face mixin

blocks/init/src/blocks/wrapper/components/wrapper-editor.js, blocks/init/src/blocks/wrapper/components/wrapper-options.js, blocks/init/src/blocks/wrapper/wrapper.js
- Wrapper has option to disable its self from the start but only by code and not from editor. With this toggle you can for example add paragraph block inside a columns block and simply click on the toggle to remove wrapper and then this block behaves the same way as a normal block.
This is usefull inside innerBlocks
=> Implement ability to toggle wrapper

.github/workflows/ci.yml, .travis.yml
I see that we have Actions available, so let's give it a try 🤷‍♂️
=> Add GH action for linitng

blocks/init/src/blocks/custom/carousel-image/transforms.js, blocks/init/src/blocks/custom/columns/columns.php, blocks/init/src/blocks/custom/example/example.php, blocks/init/src/blocks/custom/image/transforms.js, scripts/components/color-palette-custom/color-palette-custom.js
* This fix removes the error when you unselect a color. With this we remove the error and can put the color selection back to default or transparent.
=> added fix for colorPalette

blocks/init/src/blocks/custom/group/group-block.js, blocks/init/src/blocks/custom/group/hooks/index.js, blocks/init/src/blocks/wrapper/components/wrapper-options.js, blocks/init/src/blocks/wrapper/manifest.json
* Group block now behaves the similar way as column block, every item inside has simplified wrapper.
* Wrapper has option to use normal or simple wrapper also option to show/hide controls for simple and normal wrapper
=> Wrapper and group options

blocks/init/src/blocks/components/button/button.php, blocks/init/src/blocks/components/heading/heading.php, blocks/init/src/blocks/components/image/image.php, blocks/init/src/blocks/components/link/link.php, blocks/init/src/blocks/components/lists/lists.php, blocks/init/src/blocks/components/paragraph/paragraph.php, blocks/init/src/blocks/components/video/video.php
additional check to not render the component if the content of url is missing. Because we have an object the component will always render.
=> adding additional check for components

blocks/init/src/blocks/custom/featured-posts/featured-posts.php
I've added a missing semicolon on the featured-posts block.
=> Add missing semicolon

CHANGELOG.md, blocks/init/src/blocks/components/video-iframe/components/video-iframe-editor.js, blocks/init/src/blocks/components/video-iframe/components/video-iframe-options.js, blocks/init/src/blocks/components/video-iframe/docs/readme.md, blocks/init/src/blocks/components/video-iframe/docs/story.js, blocks/init/src/blocks/components/video-iframe/video-iframe-style.scss, blocks/init/src/blocks/components/video-iframe/video-iframe.php, blocks/init/src/blocks/custom/vimeo/components/vimeo-editor.js, blocks/init/src/blocks/custom/vimeo/components/vimeo-options.js, blocks/init/src/blocks/custom/vimeo/docs/readme.md, blocks/init/src/blocks/custom/vimeo/docs/story.js, blocks/init/src/blocks/custom/vimeo/manifest.json, blocks/init/src/blocks/custom/vimeo/vimeo-block.js, blocks/init/src/blocks/custom/vimeo/vimeo.php, blocks/init/src/blocks/custom/youtube/components/youtube-editor.js, blocks/init/src/blocks/custom/youtube/components/youtube-options.js, blocks/init/src/blocks/custom/youtube/docs/readme.md, blocks/init/src/blocks/custom/youtube/docs/story.js, blocks/init/src/blocks/custom/youtube/manifest.json, blocks/init/src/blocks/custom/youtube/youtube-block.js, blocks/init/src/blocks/custom/youtube/youtube.php
- New video-iframe component.
- New Vimeo block.
- New Youtube block.
=> adding block

setup/create-wp-project/src/basics/command-line.js
Fixes issues:
---
* https://github.com/infinum/eightshift-frontend-libs/issues/184
* https://github.com/infinum/eightshift-boilerplate/issues/213
=> Allow spaces in paths

blocks/init/src/Blocks/components/layout-three-columns/layout-three-columns.php, blocks/init/src/Blocks/components/layout-three-columns/manifest.json
Tag will make it possible to specify different HTML tag, like header or footer for instance.
=> Add a tag to the component

styles/scss/placeholders/_all.scss, styles/scss/placeholders/_link.scss
I've added a placeholder for resetting the default browser style on anchor links.
=> Add link reset placeholder

styles/scss/functions/_em.scss, styles/scss/functions/_line-height.scss
Depends on #201 (will rebase after it's merged).
Adds the strip-units helper to the relative helpers.
=> Fix relative units

blocks/init/src/Blocks/custom/example/components/example-editor.js
Fix prop destructure in ExampleEditor component.
=> Fix editor component for the Example block

styles/override-editor.scss
- fixing icon on responsive button
- fixing multiple select size broken in the latest release from core :(
=> adding misc fixes

blocks/init/src/Blocks/components/share/assets/index.js, blocks/init/src/Blocks/components/share/assets/share.js, blocks/init/src/Blocks/components/share/components/share-editor.js, blocks/init/src/Blocks/components/share/docs/readme.md, blocks/init/src/Blocks/components/share/docs/story.js, blocks/init/src/Blocks/components/share/manifest.json, blocks/init/src/Blocks/components/share/share-style.scss, blocks/init/src/Blocks/components/share/share.php
Share component lists 4 networks that support share links.
On mobile devices should open a native share dialog.
I didn't figure out how to control the display of certain social networks in  component options, so feedback is welcome on that side.
=> Add share component

blocks/init/src/Blocks/components/card/docs/story.js, blocks/init/src/Blocks/components/card/manifest.json, blocks/init/src/Blocks/custom/accordion/manifest.json, blocks/init/src/Blocks/custom/column/manifest.json, blocks/init/src/Blocks/custom/columns/manifest.json, blocks/init/src/Blocks/custom/example/components/example-editor.js, blocks/init/src/Blocks/custom/example/example.php, scripts/editor/register-blocks.js
I have updated the fix so now you can now override component from component from component and etc.
- a few fixes on blocks and components
=> updating components

blocks/init/src/Blocks/components/image/image-style.scss, scripts/helpers/camelize.js, scripts/helpers/index.js
Changed the camelcase function to accomodate this tests:
```js
camelize('test');
camelize('test aaa');
camelize('tes t ssaf');
camelize('testIvan a');
camelize('test Ivan Ivan');
camelize('Test Ivan Ivan');
camelize('test-Ivan-Ivan');
camelize('test_Ivan_Ivan');
camelize('test_ivan Ivan');
```
=> updating new helper

blocks/init/src/Blocks/custom/columns/columns-editor.scss, blocks/init/src/Blocks/custom/columns/columns.php, blocks/init/src/Blocks/custom/columns/components/columns-editor.js, blocks/init/src/Blocks/custom/columns/styles/_shared.scss
- We had an issues with columns when there are more than one nesting level. This PR fixes this. You can nest it multiple levels and have total control
=> updating multilevel nested columns

blocks/init/src/Blocks/components/button/components/button-options.js, blocks/init/src/Blocks/components/heading/components/heading-options.js, blocks/init/src/Blocks/components/link/components/link-options.js, blocks/init/src/Blocks/components/lists/components/lists-options.js, blocks/init/src/Blocks/components/paragraph/components/paragraph-options.js, blocks/init/src/Blocks/custom/column/column-hooks.js, blocks/init/src/Blocks/custom/column/column.php, blocks/init/src/Blocks/custom/column/components/column-options.js, blocks/init/src/Blocks/custom/column/manifest.json, blocks/init/src/Blocks/custom/column/styles/_shared.scss
- Removed duplicated calls for scripts
- Added option on column to vertically align so you can get this kind of design
=> updating column with align

setup/create-wp-project/src/arguments.js, setup/create-wp-project/src/commands/plugin.js, setup/create-wp-project/src/search-replace.js, tests/unit/create-wp-project/arguments.test.js
=> Remove unnecessary stuff

setup/create-wp-project/package.json
Forgot to bump it in the previous PR https://github.com/infinum/eightshift-frontend-libs/pull/249
=> Bump NPM version

blocks/init/src/Blocks/custom/paragraph/manifest.json
Change the icon of the paragraph block.
Never understood why are we using RTL icon for paragraph tbh 👀
=> Update paragraph icon

blocks/init/src/Blocks/custom/heading/manifest.json
Changing the icon to correspond to the block.
=> Change heading icon

blocks/init/src/Blocks/components/image/components/image-options.js
Add alt attribute setting when using image placeholder in options.
=> Add alt setting when using image placeholder

setup/create-wp-project/src/arguments.js, tests/unit/create-wp-project/arguments.test.js
=> Fix namespace generation

.github/workflows/ci.yml, package.json
Added unit tests to GH actions
=> Lets try adding unit tests to actions

blocks/init/src/Blocks/components/button/assets/index.js, blocks/init/src/Blocks/components/button/button.php, blocks/init/src/Blocks/components/link/assets/index.js, blocks/init/src/Blocks/components/link/link.php
The anchor smooth scroll didn't work properly because the class was wrong set inside the `button.php` file and the selector was wrong inside the `index.js` file
=> Fix css class and selector

blocks/init/src/Blocks/components/button/components/button-options.js, blocks/init/src/Blocks/components/button/components/button-toolbar.js, blocks/init/src/Blocks/components/button/docs/story.js, blocks/init/src/Blocks/components/button/manifest.json, blocks/init/src/Blocks/components/card/components/card-options.js, blocks/init/src/Blocks/components/card/components/card-toolbar.js, blocks/init/src/Blocks/components/heading/components/heading-options.js, blocks/init/src/Blocks/components/heading/components/heading-toolbar.js, blocks/init/src/Blocks/components/heading/docs/story.js, blocks/init/src/Blocks/components/heading/manifest.json, blocks/init/src/Blocks/components/link/components/link-options.js, blocks/init/src/Blocks/components/link/components/link-toolbar.js, blocks/init/src/Blocks/components/link/docs/story.js, blocks/init/src/Blocks/components/link/manifest.json, blocks/init/src/Blocks/components/paragraph/components/paragraph-options.js, blocks/init/src/Blocks/components/paragraph/components/paragraph-toolbar.js, blocks/init/src/Blocks/components/paragraph/docs/story.js, blocks/init/src/Blocks/components/paragraph/manifest.json, blocks/init/src/Blocks/custom/card/components/card-options.js, blocks/init/src/Blocks/custom/card/components/card-toolbar.js, blocks/init/src/Blocks/custom/card/manifest.json, scripts/editor/get-options.js, scripts/editor/index.js
Feature is the same as on this PR https://github.com/infinum/eightshift-frontend-libs/pull/289 but more streamed in the eightshift way
=> adding implementation to the helper

webpack/base.js, webpack/helpers.js, webpack/index.js, webpack/storybook.js
This is just a little update for webpack. Nothing to do with css variables
=> adding option for css variables

blocks/init/src/Blocks/components/heading/manifest.json, scripts/editor/output-css-variables.js
adding options to convert css variable output to color, select-variable, boolean-variable and default. also option to add any css variable no mater the manifest
=> updating helper for css variables

.github/workflows/ci.yml, scripts/editor/output-css-variables.js, scripts/editor/paste-handler.js, scripts/helpers/camelize.js, webpack/base.js
As per #300, node is EOL so we can remove the support. Basically they only thing we do is we no longer run tests on node 10.
Changelog
---
* Fixes #300 
* Fixes #307
=> No longer run tests on node 10, but add node 15

scripts/components/custom-select/custom-select.js, scripts/components/custom-select/docs/readme.mdx, scripts/components/custom-select/docs/story.js
Allows Custom select to have asynchronously loaded options via a callback function.
More info in the Storybook readme and stories.
=> Custom select async option

scripts/editor/output-css-variables.js
- final custom-responsive css variable
```json
{
"attributes": {
"mediaAlign": {
"type": "string",
"default": "center center",
"variable": "custom-responsive"
},
},
"options": {
"mediaAlign": {
"bottom right": [
{
"variable": {
"novi": "cool"
}
},
{
"breakpoint": "tablet",
"variable": {
"test": "ivan",
"testNovi": "%value%",
"horizontal": "flex-end",
"vertical": "flex-end"
}
}
]
}
}
}
```
=> updating responsive-select

scripts/editor/index.js, scripts/editor/output-css-variables.js
- at this point just don't ask why
=> updating variables

blocks/init/src/Blocks/components/accordion/components/accordion-editor.js, blocks/init/src/Blocks/components/button/components/button-options.js, blocks/init/src/Blocks/components/heading/components/heading-options.js, blocks/init/src/Blocks/components/icon/components/icon-options.js, blocks/init/src/Blocks/components/lists/components/lists-options.js, blocks/init/src/Blocks/components/paragraph/components/paragraph-editor.js, blocks/init/src/Blocks/components/paragraph/components/paragraph-options.js, blocks/init/src/Blocks/components/social-links/components/social-links-editor.js, blocks/init/src/Blocks/components/video-button/components/video-button-editor.js, blocks/init/src/Blocks/components/video/components/video-options.js, scripts/editor/output-css-variables.js, scripts/editor/props.js, scripts/editor/register-blocks.js
If this is not working I'm going to kill myself if it is working I'm going to get so drunk so win win.
=> updating props helper

blocks/init/src/Blocks/components/button/button.php, blocks/init/src/Blocks/components/card/card.php, blocks/init/src/Blocks/components/head/head.php, blocks/init/src/Blocks/components/heading/heading.php, blocks/init/src/Blocks/components/image/image.php, blocks/init/src/Blocks/components/jumbotron/jumbotron.php, blocks/init/src/Blocks/components/lists/lists.php, blocks/init/src/Blocks/components/paragraph/paragraph.php, blocks/init/src/Blocks/components/video/video.php, blocks/init/src/Blocks/custom/accordion/accordion.php, blocks/init/src/Blocks/custom/button/button.php, blocks/init/src/Blocks/custom/card/card.php, blocks/init/src/Blocks/custom/column/column.php, blocks/init/src/Blocks/custom/columns/columns.php, blocks/init/src/Blocks/custom/featured-categories/featured-categories.php, blocks/init/src/Blocks/custom/featured-posts/featured-posts.php, blocks/init/src/Blocks/custom/heading/heading.php, blocks/init/src/Blocks/custom/image/image.php, blocks/init/src/Blocks/custom/jumbotron/jumbotron.php, blocks/init/src/Blocks/custom/lists/lists.php, blocks/init/src/Blocks/custom/paragraph/paragraph.php, blocks/init/src/Blocks/custom/video/video.php, scripts/editor/output-css-variables.js, styles/scss/functions/_calc-grid-width.scss, styles/scss/mixins/_modifiers-range.scss
FIxes #345 
I've fixed the phpcs escape codes (added where they were missing), dart sass issues and some inconsistency in the outputCssVariables function.
=> Fix escaping issues

scripts/editor/output-css-variables.js
Same fix as https://github.com/infinum/eightshift-libs/pull/205
=> No need to skip empty variables

scripts/editor/props.js, scripts/editor/register-blocks.js
- updating get_attributes method for prop drilling and prefixing attributes
=> updating get attributes method for nesting

scripts/editor/props.js, scripts/helpers/check-attr.js, scripts/helpers/index.js
- updating props helper for better drilling in combination with the previous PR #378
- updating checkAttr helper to use parent prefix if it is used.
- making a new helper for saving values in the setAttributes function
=> refactoring props helper for new attribute prefixes way

blocks/init/src/Blocks/components/button/components/button-options.js, blocks/init/src/Blocks/components/card/components/card-options.js, blocks/init/src/Blocks/components/card/components/card-toolbar.js, blocks/init/src/Blocks/components/heading/components/heading-options.js, blocks/init/src/Blocks/components/lists/components/lists-options.js, blocks/init/src/Blocks/components/paragraph/components/paragraph-options.js, scripts/editor/get-options.js
adding necessary corrections for component/blocks.
update:
even simpler with no need for options key in function attrs.
=> adding component/blocks corrections for new options helper

scripts/editor/register-blocks.js
Changelog:
- added showWrapper as an exception for not adding component/block name to attribute name
=> Fix for showWrapper attributes

blocks/init/src/Blocks/components/layout-three-columns/layout-three-columns.php, blocks/init/src/Blocks/components/menu/menu.php
They are probably false positives, but just renaming the variables fixes the issue.
=> Fix the phpcs errors

scripts/components/icon-toggle/icon-toggle.js, scripts/components/index.js, styles/override-editor.scss
Last ones, I promise 😄 
Some things you can't see from Storybook 😄
=> Couple more bugfixes

blocks/init/src/Blocks/wrapper/components/wrapper-options.js, scripts/components/responsive/docs/story.js
This was throwing errors for some reason for me just out of the blue, so just adding a `?.` before the value seems to do the trick.
=> Fix the possible undefined value

scripts/editor/index.js, scripts/editor/register-blocks.js
Fix block and variation rendering
=> Fix storybook

blocks/init/src/Blocks/assets/scripts/application-blocks-editor.js
A PHP filter will be added to the libs.
Co-authored-by: Ivan Ruzevic <ivan.ruzevic@infinum.hr>
=> Add paragraph as a default block in the editor

scripts/components/custom-select/custom-select.js
Main improvement: **`simpleValue` now also works with async versions of CustomSelect**!
Besides that, new passthrough-able attributes were added:
- `disabled`: if set to `true`, renders the component as disabled.
- `loading`: if set to `true`, renders the component in a loading state.
- `blurInputOnSelect`: if set to `true`, focus is removed from the input once an option is selected.
- `hideSelected`: if set to `true`, the selected option is hidden from the menu.
- `loadingMessage`: text to display when loading options.
- `noOptionsMessage`: text to display when no options are available
=> CustomSelect improvements

scripts/components/custom-select/custom-select.js
Fix one 'minor' bug where a simple selected dropdown didn't work.
=> Fix simple value select not being selected

scripts/helpers/debounce.js, scripts/helpers/index.js, scripts/helpers/throttle.js
Connected with issue #511 
Changelog:
- docs in - scripts/helpers/debounce.js
- default value - scripts/helpers/debounce.js
- added throttle import - scripts/helpers/index.js
- added throttle implementation - scripts/helpers/throttle.js
=> Feature - Throttle implementation

scripts/components/custom-select/custom-select.js
Fixes an issue when cache is trying to be set if it doesn't exist and when trying to read from a cache that doesn't exist.
=> Custom select cache nullguard

scripts/components/custom-select/custom-select.js
After some torture with all the fun aspects of JS, hopefully we're good now with CustomSelect, all its combinations and ways of fetching and caching data 😄
=> CustomSelect cache retreival fix

blocks/init/src/Blocks/custom/carousel/assets/carousel-slider.js, blocks/init/src/Blocks/custom/carousel/carousel-style.scss, blocks/init/src/Blocks/custom/carousel/carousel.php, package.json
Swiper is updated to ^7.3.1
Fixed css imports
Fixed swiper wrapper class
Fixed way of importing modules for Swiper
=> Update Swiper to version 7

blocks/init/src/Blocks/assets/scripts/application-blocks-editor.js, scripts/editor/register-blocks.js
This file gives you the option to any override block manifest value by providing the same key.
With this feature you can pass anything from PHP using translation variables to JS and do some kind of conditions with that.
=> adding overrides option in block registration

scripts/index.js
Trying to find a better way to export all the scripts at once.
I couldn't find any better solution than this one. Hopefully, someone will be able to improve it.
Screen recording:
https://user-images.githubusercontent.com/46056662/149733232-d5e66d8a-2c7e-4338-8799-350349fb5080.mov
https://user-images.githubusercontent.com/46056662/149733315-fdcd160a-3531-4673-aef7-463d09380b46.mov
https://user-images.githubusercontent.com/46056662/149733272-1cf81038-cdfa-4cd1-a628-2298bb4779f5.mov
This PR Closes #537
=> Script reference improvement

scripts/components/custom-select/custom-select.js, scripts/components/custom-select/docs/readme.mdx, scripts/editor/fetch-wp-api.js
Changelog:
- add processMetadata option to fetch-wp-api
- add filter async options function to custom select
Result:
- ability to adjust, filter, group, etc. dynamically fetched options in custom select
- ability to get additional field(s) from WP API to enrich fetch-wp-api return object
Issue #531
=> Async options filtering in CustomSelect component

package.json
Move swiper from devDependencies to dependencies since I've accidentally put swiper inside devDependencies
=> Move swiper from devDependencies to dependencies

blocks/init/src/Blocks/manifest.json, schemas/settings.json
Just like previous PR this is schema for global setting manifest.json
=> adding global setting schema

package.json, scripts/components/custom-slider/custom-range-slider.js, scripts/components/custom-slider/custom-slider.js, scripts/components/custom-slider/custom-slider.scss, scripts/components/custom-slider/docs/readme.mdx, scripts/components/custom-slider/docs/story.js, scripts/components/index.js, scripts/index.js, styles/storybook.scss
Adds new `CustomSlider` and `CustomRangeSlider` components with a truckload of options (check the doc comments and the stories 😉 )
https://user-images.githubusercontent.com/77000136/152543486-050b7cfa-857b-4a70-9d63-057ecdbcaeb8.mov
https://user-images.githubusercontent.com/77000136/152543516-5a13b929-8cd1-4db4-ba79-9ad3cc3eeceb.mov
\-
=> CustomSlider and CustomRangeSlider

scripts/components/custom-slider/custom-range-slider.js, scripts/components/custom-slider/custom-slider.js, scripts/components/index.js, styles/override-editor.scss
Fixes a couple of JS exports and CSS import issues.
\-
\-
=> Custom slider fixes

blocks/init/src/Blocks/components/hamburger/hamburger.php, blocks/init/src/Blocks/components/modal/modal.php
Fixes the wrong text domain in `hamburger.php` (🙈) and wraps a string in `__` in `modal.php`.
=> Fix text domains

styles/es-component-styles.scss, styles/es-utility-classes.scss
Changes:
- tweaked a couple of utility classes
- reordered imports to make sure rc-slider styles are always first
\-
\-
=> Minor style fixes

scripts/plugins/yoast-seo.js
- different way of setting this up
- it analyses frontend html code
=> adding fixes for yoast seo plugin analize

blocks/init/src/Blocks/manifest.json, schemas/globalManifest.json, scripts/editor/registration.js, scripts/editor/store.js
- added option to not use wrapper all together
=> adding option to remove wrapper

scripts/components/advanced-color-picker/advanced-color-picker.js
- add GradientPicker component with fallback for versions prior to 5.9
=> Fix Gradient Picker component

scripts/editor/registration.js, scripts/editor/store.js
- added variations to the store.
https://github.com/infinum/eightshift-libs/pull/299
=> adding variations to store

setup/create-wp-project/src/basics/argument-operations.js, setup/create-wp-project/src/basics/command-line.js, setup/create-wp-project/src/commands/theme.js
Add checks for requirements before theme setup starts.
System requirements check passed successfully:
Check fails if composer is not installed:
latest updated:
=> Add checks for requirements

blocks/init/src/Blocks/custom/carousel/manifest.json, blocks/init/src/Blocks/custom/columns/manifest.json, blocks/init/src/Blocks/custom/group/manifest.json
- adding new flag in manifest for innerBlocksDependency that will tell the cli to include this in the process
=> adding inner blocks depenedency

setup/create-wp-project/src/arguments.js, tests/unit/create-wp-project/basics/argument-operations.test.js
=> Fix the project name in case of extra spaces

scripts/components/custom-slider/custom-slider.scss
This PR fixes display options of a custom slider in Firefox browser. 
1. Fix options display for Firefox browser
2. Align other browser to look the same
=> Custom Slider Component - Fix options display

scripts/components/simple-repeater/simple-repeater.js
Changes:
- added callbacks for customizing add item and drag/reorder behavior
\-
\-
=> [8.0.0] SimpleRepeater enchacements

blocks/init/src/Blocks/custom/columns/manifest.json, scripts/components/number-picker/number-picker.js
- Spinners in `NumberPicker` will now set the `min` value if no value is currently present (`undefined` or empty value)
- Columns will now hide the full wrapper option
=> Frontend libs 8.2.1

blocks/init/src/Blocks/components/load-more/docs/readme.mdx, blocks/init/src/Blocks/custom/featured-categories/components/featured-categories-editor.js, blocks/init/src/Blocks/custom/featured-content/featured-content.php, blocks/init/src/Blocks/custom/featured-content/partials/cards.php, scripts/editor/registration.js, scripts/helpers/throttle.js, scripts/plugins/yoast-seo.js, styles/scss/functions/_calc-column-width.scss, styles/scss/functions/_calc-dynamic-size.scss, styles/scss/functions/_calc-grid-width.scss, styles/scss/functions/_global-config.scss, styles/scss/functions/_global-settings.scss, styles/scss/functions/_line-height.scss, styles/scss/functions/_map-get-deep.scss, styles/scss/functions/_map-get-strict.scss, styles/scss/functions/_map-reverse.scss
- Short aliases for all functions in scss helpers because I'm to lazy to write.
- Upgraded Yoast SEO plugin helper from Infinum web.
- Upgraded throttle helper from Infinum web.
- Removing unnecesery "blockSsr" attribute.
- Added `viewportWidth` to the example.
=> adding scss and helpers

webpack/base.js
=> Add webp support for build

scripts/editor/hooks.js
- adding fix that broke WooCommerce blocks
=> Adding fixes for WooComerce

blocks/init/src/Blocks/components/load-more/assets/index.js
=> Tweak Load more

CHANGELOG.md, blocks/init/src/Blocks/wrapper/manifest.json, blocks/init/src/Blocks/wrapper/wrapper.php, package.json
- `wrapper` corrections to be used using the `render` method as a standalone component.
=> Added a standalone wrapper options

CHANGELOG.md, package.json
@iruzevic did a squash boo-boo so we have to merge main now, otherwise it's merge conflict heaven.
=> Release 9.5.0 - fix squash

CHANGELOG.md, package.json, styles/wp-version-specific/_wp-6-5.scss
Gotta love WP 6.5 not-immediately-obvious changes 😄 
- Fixed block editor sidebar block display with long labels
=> Frontend libs 11.0.1

CHANGELOG.md, bun.lock, package.json, scripts/components/advanced-color-picker/advanced-color-picker.js, scripts/components/block-inserter/block-inserter.js, scripts/components/file-pickers/file-picker.js, scripts/components/picker-placeholder/picker-placeholder.js, scripts/components/repeater/sortable-item.js, scripts/components/responsive/responsive.js, scripts/components/section/section.js, scripts/components/server-side-render/server-side-render.js, scripts/components/width-offset-range-slider/width-offset-range-slider.js
- Updating all component to correspond to latest https://github.com/infinum/eightshift-ui-components release with migration guide https://eightshift.com/components/es-ui-components/migrations
=> updating dependencies and migrating ui-components
