CHANGELOG.md, webpack/base.js
adding cleanStaleWebpackAssets to CleanWebpackPlugin in webpack to fix removal of files being added by CopyWebpackPlugin in watch mode
=> Fixing CleanWebpackPlugin

blocks/init/components/paragraph/components/paragraph-options.js
Inside the options for the paragraph block the Paragraph Font Size showed `Small (20px)` but under the `paragraph-style.scss` it was set to 18px.
=> change small size text on paragraph options

CHANGELOG.md, scripts/register-block.js
Added block manifest registration ability to register blocks in different namespace than global settings.
By default all blocks take namespace from global namespace but now you can provide namespace in each block and it will take that as default.
also I have fixed change-log a little bit.
This is in combination with PR on the Eightshift-Libs (https://github.com/infinum/eightshift-libs/pull/43)
=> Added block manifest registration

CHANGELOG.md, webpack/aliases.js
- added new alias `EightshiftBlocksSwiperIE` for Swiper slider support in IE 11 browser
=> Add new alias for swiper with IE11 support

CHANGELOG.md, blocks/init/assets/styles/parts/utils/_z-index.scss, blocks/init/src/blocks/components/copyright/docs/readme.md, blocks/init/src/blocks/components/drawer/drawer-style.scss, blocks/init/src/blocks/components/drawer/drawer.php, blocks/init/src/blocks/components/footer/docs/readme.md, blocks/init/src/blocks/components/footer/footer-style.scss, blocks/init/src/blocks/components/footer/footer.php, blocks/init/src/blocks/components/hamburger/docs/readme.md, blocks/init/src/blocks/components/hamburger/hamburger-style.scss, blocks/init/src/blocks/components/hamburger/hamburger.php, blocks/init/src/blocks/components/header/docs/readme.md, blocks/init/src/blocks/components/header/header-style.scss, blocks/init/src/blocks/components/header/header.php, blocks/init/src/blocks/components/logo/docs/readme.md, blocks/init/src/blocks/components/logo/logo-style.scss, blocks/init/src/blocks/components/menu/components/horizontal/menu-horizontal-style.scss, blocks/init/src/blocks/components/menu/components/vertical/menu-vertical-style.scss, blocks/init/src/blocks/components/menu/docs/readme.md, blocks/init/src/blocks/components/page-overlay/docs/readme.md, blocks/init/src/blocks/components/page-overlay/page-overlay-style.scss, blocks/init/src/blocks/components/page-overlay/page-overlay.php, blocks/init/src/blocks/components/scroll-to-top/assets/index.js
This build was seriously broken.
* Wrong namespace in components helpers.
* Removing unnecessary map keys for components style.
* Fixing drawer styles.
* Fixing menu styles.
* Loading z-index from external map.
* Fixing typo translate3D to translate3d.
* Removing display: inline-block;
* Fixing logo styles.
* Fixing broken scroll to top method.
=> Fixing broken build

CHANGELOG.md, blocks/init/src/blocks/components/drawer/assets/drawer.js, blocks/init/src/blocks/components/drawer/drawer-style.scss, blocks/init/src/blocks/components/footer/footer-style.scss, blocks/init/src/blocks/components/header/header-style.scss, blocks/init/src/blocks/components/menu/components/horizontal/menu-horizontal-style.scss
Changelog
---
* Added support for `behind` and `top` drawers / mobile menus (slide from top or fade in)
* Better vertical / horizontal centering (more `flex`, less `height`, proper justifying)
* Removed some `height: 100%` which made styling links difficult and coupled to header / footer height
* Fixed a bug with centering where logo wouldn't be quite centered on mobile - seemingly due to having `flex-basis` set to auto. Setting it to any other value (such as `1px`) fixed the issue.
* Fixed a bug where `drawer` wouldn't work if `page-overlay` did not exist
=> Tweak header components

styles/scss/placeholders/_all.scss
`absolute-center` placeholder was added (and it's in sassdoc) but wasn't imported.
=> Import absolute-center placeholder.

CHANGELOG.md, blocks/init/src/blocks/components/scroll-to-target/assets/index.js, blocks/init/src/blocks/components/scroll-to-target/components/scroll-to-target-editor.js, blocks/init/src/blocks/components/scroll-to-target/components/scroll-to-target-options.js, blocks/init/src/blocks/components/scroll-to-target/docs/readme.md, blocks/init/src/blocks/components/scroll-to-target/docs/story.js, blocks/init/src/blocks/components/scroll-to-target/scroll-to-target-style.scss, blocks/init/src/blocks/components/scroll-to-target/scroll-to-target.php
Add scroll-to-target component that works similar to scroll-to-top component
Component has options for defining target of the scroll action and text of the scroll-to link.
It works by getting the `href` attribute and scrolling to element with matching `id` attribute
=> Scroll to target component

CHANGELOG.md, blocks/init/src/blocks/components/button/components/button-options.js, blocks/init/src/blocks/components/heading/components/heading-options.js, blocks/init/src/blocks/components/link/components/link-options.js, blocks/init/src/blocks/components/paragraph/components/paragraph-options.js, blocks/init/src/blocks/custom/divider/components/divider-options.js, components/color-palette-custom/color-palette-custom.js, components/color-palette-custom/docs/readme.md, index.js, scripts/get-pallete-colors.js
Changelog
---
* `editor-color-pallete` - Modified the `ColorPaletteCustom` component to get colors by default from WordPress's global store
* `editor-color-pallete` - Modified all uses of `ColorPaletteCustom` component to not override default colors (except for wrapper)
* `editor-color-pallete` - Added a helper (using React hooks) for reading colors from WordPress's global store in `scripts/get-pallete-colors.js`
* Added docs for `editor-color-pallete`
These changes are backwards compatible with existing blocks setting colors "the old way" and nothing should break if you were to update libs on an existing project.
Also instead of using `useSelect` (which isn't supported on WP < 5.3), I've used `withSelect` HOC on `ColorPaletteCustom` which should work everywhere. There's a helper which …
=> Editor color pallete

scripts/editor/get-actions.js
- Added ability to automatically build only 1 action for `type: 'object'` attributes by setting `multipleProps: false` for that attribute in manifest.
- Fixed some typos
=> Allow single action objects

CHANGELOG.md, scripts/editor/get-actions.js
Now we no longer need to add `multipleProps: true / false` for `type: object` attributes. `getActions()` now returns both (whole object setters + individual property setters) and you can just pick and choose which ones you need.
=> Simplify getActions

styles/scss/placeholders/_all.scss
`%visually-hidden` placeholder wasn't added to `_all.scss`
=> Add visually hidden placeholder to all.scss

styles/scss/functions/_all.scss, styles/scss/functions/_em.scss, styles/scss/functions/_line-height.scss
As the title suggests. Takes the value that should be in pixels, and converts it to em. 
Using ems is cool because when you zoom the site, everything scales up quite nicely 🙂
=> Add relative helpers for line height and em calculation

blocks/init/src/Blocks/components/heading/manifest.json, blocks/init/src/Blocks/custom/column/manifest.json, blocks/init/src/Blocks/custom/columns/manifest.json, blocks/init/src/Blocks/wrapper/manifest.json
We had incorrect attribute type for all numeric attributes, which produced errors when attribute was changed.
This happens on fresh BP installation, installed with:
`npx create-wp-project --eightshiftBoilerplateBranch="release/5.0.0"`
```
PHP Notice:  rest_validate_value_from_schema was called <strong>incorrectly</strong>. The "type" schema keyword for  can only be one of the built-in types: array, object, string, number, integer, boolean, and null.
```
Can someone please double check this before this is merged.
=> Fix attribute type

blocks/init/src/Blocks/components/accordion/accordion.php, blocks/init/src/Blocks/components/accordion/assets/accordion.js, scripts/helpers/element-children-height.js, scripts/helpers/index.js
Add a helper method for calculating height of the element based on the combined height of its children.
Update accordion functionality to expand the accordion content by the correct height (instead of fixed one).
Fix accordion JS class
=> Accordion component update

blocks/init/src/Blocks/components/head/head.php
`bloginfo()` echoes the value. When you try to echoe it again inside the meta element, the whole `<head>` breaks.
`get_bloginfo()` returns the value.
=> Replace bloginfo() with get_bloginfo()

styles/scss/mixins/_all.scss, styles/scss/mixins/_inline-font-colors.scss
There is an option in the `RichText` component to add several different toolbars to it. One of them is the `text-color`
```js
<RichText
className={headingClass}
placeholder={placeholder}
value={headingContent}
onChange={(value) => setAttributes({ [`${componentName}Content`]: value })}
formattingControls={['bold', 'text-color']}
/>
```
This will give you the ability to color certain parts of the word in the component. For instance, for the heading component this will look like this:
Based on what colors you specify in your component map, you can pass this map to the mixin and it will automatically generate the necessary predefined Gutenberg classes (`.has-{colorName}-color` format).
=> Add inline font color mixin

package.json
Added missing `browser-sync` package to `package.json` because of dependency for the `browser-sync-webpack-plugin` package.
=> Add browser sync to package.json

babel/babel.config.js, package-lock.json, package.json, webpack/base.js
- without this fix the DependencyExtractionWebpackPlugin will put everything with @wordpress prefix as a global and we don't want that on the frontend
=> updating Webpack externals

blocks/init/src/Blocks/components/video/components/video-options.js
Fix typo in `videoType` attribute name
Add `help` property to the `videoType` select component
Remove `videoUrl` from `onChange` method of  `videoType` select component
=> Fix onChange property for videoType attribute.

blocks/init/src/Blocks/custom/column/components/column-options.js, blocks/init/src/Blocks/custom/column/manifest.json
The `Offset` property on column was not settable to `0`, which can sometimes be inconvenient, eg. when doing responsive offsets.
This PR adds a new entry into the manifest options and makes the Offset's RangeControl use min/max/step from that new entry.
=> make offset on Columns settable to 0

blocks/init/src/Blocks/custom/column/column.php, blocks/init/src/Blocks/custom/column/components/column-options.js, blocks/init/src/Blocks/custom/column/manifest.json
The `order` property in the column options is saved properly, but because the Responsive selectors in `columns.php` were set **not** to use modifiers, the actual value wasn't being reflected in the outputted classes.
=> Fix order value not being applied on Columns

babel/babel.config.js, package.json, scripts/editor/get-option-colors.js, tests/unit/scripts/editor/optionColors.test.js
Added a helper that can be used in components to select only the colors defined in the component/block `manifest.json`. For instance if we have a component and inside we have 
```json
{
"componentName": "some-component",
"title": "Some Component",
"componentClass": "some-component",
"components": {
"heading": "heading",
"button": "button"
},
"options": {
"colors": [
"primary",
"secondary",
"tertiary",
"maiden",
"stratos",
"caribbean",
"white",
"transparent"
]
}
}
```
and in the global manifest we have 
```json
{
"namespace": "eightshift-boilerplate",
"background": "#05A8AA",
"foreground": "#FFFFFF",
"globalVariables": {
"customBlocksName": "eightshift-block",
"maxCols": 12,
"breakpoints": {
"small": 320,
"mobile": 767,
"tablet": 991,
"desktop": 1199,
"large": 1200
},
"containers": { …
```
=> Add component color helper

blocks/init/src/Blocks/components/accordion/manifest.json, blocks/init/src/Blocks/components/button/manifest.json, blocks/init/src/Blocks/components/copyright/manifest.json, blocks/init/src/Blocks/components/heading/manifest.json, blocks/init/src/Blocks/components/link/manifest.json, blocks/init/src/Blocks/components/lists/manifest.json, blocks/init/src/Blocks/components/paragraph/manifest.json, blocks/init/src/Blocks/components/scroll-to-top/manifest.json, scripts/editor/index.js, scripts/editor/yoast-seo.js
Related to this issue https://github.com/infinum/eightshift-frontend-libs/issues/231
I have adde an script that you should just call in your `application-block-editor.js` like this:
```js
import { yoastSeo } from '@eightshift/frontend-libs/scripts/editor';
yoastSeo();
```
This helper will search all blocks and components manifests and find attributes that have `"seo": "true"` key.
This key will be added in to the content and proceed by the YoastSeo Analysis plugin.
=> Adding Yoast Seo helper

blocks/init/src/Blocks/custom/accordion/manifest.json, blocks/init/src/Blocks/custom/button/manifest.json, blocks/init/src/Blocks/custom/card/manifest.json, blocks/init/src/Blocks/custom/carousel/manifest.json, blocks/init/src/Blocks/custom/column/manifest.json, blocks/init/src/Blocks/custom/columns/manifest.json, blocks/init/src/Blocks/custom/example/manifest.json, blocks/init/src/Blocks/custom/featured-categories-posts/manifest.json, blocks/init/src/Blocks/custom/featured-categories/manifest.json, blocks/init/src/Blocks/custom/featured-posts/manifest.json, blocks/init/src/Blocks/custom/group/manifest.json, blocks/init/src/Blocks/custom/heading/manifest.json, blocks/init/src/Blocks/custom/image/manifest.json, blocks/init/src/Blocks/custom/jumbotron/manifest.json, blocks/init/src/Blocks/custom/link/manifest.json, blocks/init/src/Blocks/custom/lists/manifest.json, blocks/init/src/Blocks/custom/paragraph/manifest.json, blocks/init/src/Blocks/custom/video/manifest.json, blocks/init/src/Blocks/manifest.json, blocks/init/src/Blocks/variations/button-block/manifest.json, blocks/init/src/Blocks/variations/card-simple/manifest.json
Closes #257.
- new block icons
- color scheme change from red-white to white-eightshiftBlack
Exported, minified and optimized icons not currently used (but still on the list below) will be a `.txt` file on Drive.
Icon list:
=> Block icon updates

webpack/development.js, webpack/helpers.js, webpack/index.js
I have updated the Webpack so you can now in webpack.config.js provide only useSsl: true key and it will automatically convert browserSync to https. No need for custom setup
=> updating browserSync https

webpack/base.js
DependencyExtractionWebpackPlugin outputs file to manage dependencies internally. I have switched this to json file
https://www.npmjs.com/package/@wordpress/dependency-extraction-webpack-plugin
=> updating fix to remove php file from build

blocks/init/src/Blocks/custom/featured-posts/manifest.json
There is a reference to `options.breakpoints` inside the `featured-posts-options.js` component. Without the options in the manifest, this breaks the implementation.
=> Add options to feature-posts manifest

blocks/init/src/Blocks/components/image/image-style.scss
Probably caused by changing flexbox orientation in https://github.com/infinum/eightshift-frontend-libs/commit/c92d5d525bb428312854db2f0a0bdf75ce38082c commit
Changelog:
- image alignment fix
Screenshots:
=> Fixed image alignment

.gitignore, setup/create-wp-project/package.json, setup/create-wp-project/src/basics/command-line.js, setup/create-wp-project/src/commands/plugin.js, setup/create-wp-project/src/commands/theme.js, setup/create-wp-project/src/dependencies.js
Changelog
---
* Fixes #312 (allow proper overwriting of libs / frontend libs branches during setup using `--eightshiftLibsBranch` and `--eightshiftFrontendLibsBranch` arguments during `npx create-wp-project`)
* Gitignore vsode workspace settings file
Note, these 2 arguments for overriding branches should only be used for testing because they will make your libs / frontend libs dependencies locked to those specific branches if you ever update your packages in the future and might break your install.
=> Fix setup script overriding libs and frontend libs branches

scripts/editor/register-blocks.js, styles/override-editor.scss
Fixes #265
- on block registration 2 new CSS variables (`--eightshift-block-icon-foreground` and `--eightshift-block-icon-background`) are set, corresponding to global block icon foreground/background colors
- icon background shows correct colors now if no transforms are available on the block (see image)
- tweaked spacings and alignments of icons to make them look a bit better and not be too close to backplate edges (see image)
=> Block icon display fixes

blocks/init/src/Blocks/components/button/components/button-options.js, blocks/init/src/Blocks/components/button/components/button-toolbar.js, blocks/init/src/Blocks/components/button/manifest.json, blocks/init/src/Blocks/components/link/components/link-options.js, blocks/init/src/Blocks/components/link/components/link-toolbar.js, scripts/components/index.js, scripts/components/link-toolbar-button/docs/readme.mdx, scripts/components/link-toolbar-button/docs/story.js, scripts/components/link-toolbar-button/link-toolbar-button.js
Closes #181.
This PR replaces the ugly old `URLInput` in the option with the fresh new `LinkInput`. As `LinkInput` itself wasn't meant to be used in an option panel, the URL picker now lies in the block toolbar (just like in stock Gutenberg).
To easily accomplish this (as there are a few elements to handle), a custom component - `LinkToolbarButton` - was created.
To use it in your blocks:
1. Import the component from FL
2. Import `useRef` and create a reference before the return function of your component
3. Add the `LinkToolbarButton` into the toolbar
Use it like this:
```jsx
<LinkToolbarButton
componentName={componentName}
url={buttonUrl}
opensInNewTab={buttonOpensInNewTab}
setAttributes={setAttributes}
anchorRef={ref}
title={label}
/>
```
In the editor it looks like this:
=> Link toolbar button

blocks/init/src/Blocks/components/link/link.php
Closes #305.
Because the link was rendering as a `<link>` when no URL was provided, which is wrong in many ways, this PR tweaks the Link component not to show anything if no URL or content is provided, otherwise it renders the normal `<a>` tag.
=> Make Link semantically correct

blocks/init/src/Blocks/components/icon/components/icon-options.js, blocks/init/src/Blocks/components/icon/icon-editor.scss, blocks/init/src/Blocks/components/icon/manifest.json, scripts/components/custom-select/custom-select.js, scripts/components/custom-select/docs/readme.mdx, scripts/components/custom-select/docs/story.js
This PR brings 2 new things:
1. A way to render custom dropdown item and (single) value display components in `CustomSelect`
2. Enabled by 1., a new icon picker for the `icon` component (demo below)
https://user-images.githubusercontent.com/77000136/116115880-d30e7500-a6ba-11eb-8157-ca7c4ed1bf17.mov
More details in the Storybook documentation.
=> Icon new picker (and more CustomSelect goodies)

scripts/helpers/check-attr.js
Changelog:
- check-attr.js
- added optional undefinedAllowed parameter on checkAttr function
- removed else hance early exit
In admin options, while creating responsive attributes it appeared that we can't "force" attributes to unset the value so it can inherit from other breakpoints. That's why I added this optional parameter which can be used if it is ok for you to set values to `undefined`.
This change is only important on the admin side while setting the attributes. I believe that there is no need to make these changes on PHP part(eightshift-libs). However, if you feel like we should make it exactly the same, feel free to write to me or comment down here on PR.
Screen Shots and Screen Recordings of the use case scenario
https://user-images.githubusercontent.com/46056662/118799704-53319 …
=> Optional undefinedAllowed parameter on checkAttr

styles/override-editor.scss
Adds a nice placeholder when there are no blocks inside `InnerBlocks` and makes the default appender easier to press.
https://user-images.githubusercontent.com/77000136/119648904-49210b80-be22-11eb-9ffa-45cc1df2a2e7.mov
=> Empty placeholder fix

package.json, styles/scss/functions/_calc-column-width.scss
Fixing issue with not building storybook on libs due to usage of div.math function i sass because this function is available only from sass 1.33.0
=> fixing packages version

scripts/editor/output-css-variables.js
Changelog:
- added CSS variables(variablesEditor) for only editor use
- renamed general editor only variables to variablesCustomEditor
Usage:
When there is a specific behavior that you want to override in the editor part, but keep everything in place for frontend part.
An example of behavior is under screenshots and screenrecording.
How to:
It behaves exactly the same as `variables` key from manifest. It will always override the `variables` with the same "key" because it's outputting afterward.
Screenshots and screenrecording:
https://user-images.githubusercontent.com/46056662/119996776-58918780-bfcf-11eb-9ea4-d635e349bfb1.mov
=> Add variablesEditor to Manifest

scripts/editor/props.js
Fixed a bug where props would throw a warning if you had a block (let's say `example`) but you don't have an `example` component in your project.
=> Fix props logic

scripts/editor/props.js
The `props` helper was manifesting some weird behaviour with renaming some attribute names in nested components (for example (component1 -> component2 -> component3), so I switched it to use the safer `.replace()` method, which prevents slicing and dicing component names.
=> Props helper attribute renaming fix

scripts/editor/output-css-variables.js
What this functionality brings is no need to rewrite the same values for each breakpoint in attributes, but to collect them as one in `variables` and reference all the breakpoints in `responsiveAttributes`. This brings us fewer points of a potential mistake(no need to enter the same code for each breakpoint), shortens the coding time(copying and correcting breakpoint name), shortens the code(images ⬇️ , wrapper 957 -> 491 LOC), and makes it altogether more simple to develop.
Specificity from the least specified to the most specified:
variables found in responsiveAttributes
variables
variablesEditor found in responsiveAttributes
variablesEditor
You can specify for example: `wrapperWidth` in `responsiveAttributes` and in `variables` but if you need something special or you need to override …
=> Responsive variables

.github/workflows/ci.yml, __mocks__/@eightshift/frontend-libs/mocks/wrapper.js, __mocks__/@eightshift/frontend-libs/scripts/editor.js, __mocks__/@eightshift/frontend-libs/scripts/helpers.js, __mocks__/@wordpress/block-editor.js, __mocks__/@wordpress/blocks.js, __mocks__/@wordpress/element.js, __mocks__/react-html-parser.js, babel/babel.config.js, package.json, scripts/editor/icons/icons.js, scripts/editor/register-blocks.js, tests/data/block-attributes.js, tests/data/props-output.js, tests/data/src/Blocks/components/mock-blockquote/manifest.json, tests/data/src/Blocks/components/mock-card/manifest.json, tests/data/src/Blocks/components/mock-paragraph/manifest.json, tests/data/src/Blocks/components/mock-typography/manifest.json, tests/data/src/Blocks/custom/mock-blockquote/manifest.json, tests/helpers/blocks.js, tests/unit/blocks/blockRegistration.test.js, tests/unit/scripts/editor/ucfirst.test.js
Setup JS tests for the following (currently will fail because props changes haven't been merged):
* Block registration and component attribute inheritance
* Props attribute generation on each lvl
* Both of these tests will automatically test all blocks defined in `src/init/Blocks` (actual blocks we have implemented) as well as `tests/data/src/Blocks` (mock block manifests we can use for testing some weird inheritance situations)
Block registration test
---
* We can manually define `expected` and `notExpected` attributes in each block inside `tests/data/block-attributes.js`
Props registration test
---
* We can manually define which attributes are expected / notExpected to be present in each lvl of block / component dependency tree as well as the new `prefix` attribute which is used to …
=> Setup tests

scripts/editor/register-blocks.js
Fixes a bug which happens when there's more than 1 boilerplate plugin / theme inside a project.
=> Set the subkey for each boilerplate plugin or theme

setup/create-wp-project/src/arguments.js, setup/create-wp-project/src/commands/theme.js
This PR introduces new CLI flag `--eightshiftBoilerplateRepo` that allows specifying custom Eightshift Boilerplate repository for testing external forks. Default repository remains the same (`https://github.com/infinum/eightshift-boilerplate.git`).
Example usage:
```bash
npx create-wp-project --eightshiftBoilerplateRepo https://github.com/djelic/eightshift-boilerplate.git
```
=> Make boilerplate repo configurable in cli

scripts/editor/output-css-variables.js
Changelog:
- added sort of global breakpoints in output CSS vars function
- corrected output for mobile first
Screenshots:
**What is corrected and how it used to be:**
=> Fix for responsive variables mobile first

scripts/editor/output-css-variables.js
Changelog:
- changed condition for bailout
I've noticed that one block couldn't publish only custom CSS variable(translating from wrapper variable to block variable one). So I made these changes to enable all of the prementioned variables.
Use case:
Screenshots:
=> Set only variablesCustom, variablesEditor and variablesCustomEditor

scripts/components/color-palette-custom/color-palette-custom.js
Title says it all :)
The check was set up with labels as strings, but we sometimes pass components to them.
=> Fix ColorPaletteCustom label not showing

webpack/project.js
These 2 fix the error we were having on projects with both theme + plugin using boilerplate (for example
theme + Eightshift Forms) where we would sometimes get the following error:
```
applicationBlocks.js?ver=1.0.0:64 Uncaught (in promise) TypeError: Cannot read property 'call' of undefined
at __webpack_require__
```
Fix source: https://github.com/webpack/webpack/issues/959#issuecomment-546506221
=> Fixed webpack require error

scripts/editor/index.js, scripts/editor/inserter.js
Development inserter made to insert one or multiple blocks in the dom using console.
1. Add this code in `application-blocks-editor.js` file:
```js
import { inserter } from '@eightshift/frontend-libs/scripts/editor';
*
inserter();
```
2. Open block editor and run the following commands in the console:
```js
window.eightshiftInserter.runAll();
```
- namespace prop {string} -  Namespace of blocks to insert.
- save prop {bool} [save=false] -  Save dom if true.
- reset prop {bool} [reset=false] - Reset all in dom if true.
```js
window.eightshiftInserter.runOne('full-block-name');
```
- name prop {string} - Full block name with namespace.
- save prop {bool} [save=false] - Save dom if true.
- reset prop {bool} [reset=false] - Reset all in dom if true.
```js
window.eightshiftInserter.runReset(); …
```
=> adding method for all blocks inserter

.editorconfig, .github/workflows/ci.yml, .github/workflows/tests.yml, blocks/init/src/Blocks/components/accordion/accordion.php, blocks/init/src/Blocks/components/button/button.php, blocks/init/src/Blocks/components/copyright/copyright.php, blocks/init/src/Blocks/components/heading/heading.php, blocks/init/src/Blocks/components/layout-three-columns/layout-three-columns.php, blocks/init/src/Blocks/components/menu/menu.php, blocks/init/src/Blocks/components/social-links/social-links.php, blocks/init/src/Blocks/components/video/video.php, blocks/init/src/Blocks/custom/featured-categories/featured-categories.php, blocks/init/src/Blocks/custom/featured-posts/featured-posts.php, blocks/init/src/Blocks/custom/video/video.php, blocks/init/src/Blocks/wrapper/wrapper.php, composer.json, phpcs.xml.dist, phpstan.neon.dist
I've fixed some of the PHPStanand PHPCS issues in the blocks, there are still some that are present from PHPStan. Some are false positives, some will be gone, once we release the libs with the [updated fixes](https://github.com/infinum/eightshift-libs/pull/224) and type hints. 
I've also created [stubs](https://github.com/infinum/eightshift-libs-stubs) for the FE libs (mostly for the helpers that are used in the FE libs). The stubs will need to be updated once the libs are updated so that they stay up to date.
I've also split the checks and tests for the actions and added PHPStanand PHPCS for the block view files.
And fixed as much as possible.
PHPStan checks will fail, but I've set them to be allowed failures (since most are false positives because of how the helpers in PHP are written).
=> Fix phpstan issues

scripts/editor/output-css-variables.js
Editor Version of this:
https://github.com/infinum/eightshift-libs/pull/221#issue-695750537
Desc:
There's been an issue in a case where you put "breakpoint": "mobile" in mobile-first "mode" in responsive or the largest breakpoint in the inverse: true, desktop-first responsive "mode".
The issue is resolved by adding default breakpoints recognition. By recognizing the default breakpoint, the breakpoint is reset to value 'default' which allows the variable to be set in a 'default' mode by setting the breakpoint.
=> Fix for default breakpoints

scripts/editor/icons/icons.js, scripts/editor/index.js
For some reason `BlockIcon` (component for rendering Block icons inside JSX) got removed, this PR adds it back.
=> Readding missing BlockIcon

blocks/init/src/Blocks/components/accordion/accordion.php, blocks/init/src/Blocks/components/button/button.php, blocks/init/src/Blocks/components/copyright/copyright.php, blocks/init/src/Blocks/components/drawer/drawer.php, blocks/init/src/Blocks/components/heading/heading.php, blocks/init/src/Blocks/components/layout-three-columns/layout-three-columns.php, blocks/init/src/Blocks/components/loader/loader.php, blocks/init/src/Blocks/components/menu/menu.php, blocks/init/src/Blocks/components/video/video.php, blocks/init/src/Blocks/custom/carousel/carousel.php, blocks/init/src/Blocks/custom/featured-categories/featured-categories.php, blocks/init/src/Blocks/custom/featured-posts/featured-posts.php, blocks/init/src/Blocks/wrapper/wrapper.php, phpstan.neon.dist
Some PHPStan errors have been fixed [here](https://github.com/infinum/eightshift-libs-stubs/pull/4). Having `// @phpstan-ignore-line` in code will cause error since trying to ignore error which doesn't exist. I'm removing some so the tests could be clean.
=> Remove phpstan ignore comments

scripts/components/option-picker/docs/story.js, scripts/components/simple-vertical-single-select/docs/readme.mdx, scripts/editor/override-inner-block-attributes.js
In stories, the logs are replaced by info, and in one helper it was removed. It outputted tons of info in the console. 
This one slipped through our fingers. I noticed that the linters are not picking them up, and they should. So maybe we need to fix them to catch these cases.
=> Remove console logs

styles/scss/functions/_em.scss
When doing `npm run build` on one of the projects I am getting an error:
> SassError: Undefined operation "-1 * 0.5555555556em".
> margin: 0 (-1 * map-get-strict($the-posts, 'gutter'));
The problem seems to lie inside the `em() `function which returns interpolated value. The thing is that arithmetics don't perform well when handling interpolated strings. See [here](https://github.com/dlmanning/gulp-sass/issues/611#issuecomment-375320728)
```
@function em($pixels, $context: $browser-context) {
@return #{math.div(strip-unit($pixels), strip-unit($context))}em; // shouldn't be interpolated
}
```
=> update em() for better arithmetic support

blocks/init/src/Blocks/custom/heading/heading-transforms.js, blocks/init/src/Blocks/custom/paragraph/paragraph-transforms.js
Fixes heading/paragraph transform issues by directly replacing component/block names in transforms. Skips attributes beginning with `block` (`blockName`, `blockClass` etc.)
An alternative approach would be to use the props helper to rename the component attributes as well or otherwise transform the components.
=> Fix heading <-> paragraph transform issues

blocks/init/assets/scripts/application.js, blocks/init/src/Blocks/assets/scripts/application-blocks.js
Fixes the
```
@babel/polyfill is loaded more than once on this page. This is probably not desirable/intended and may have consequences if different versions of the polyfills are applied sequentially. If you do need to load the polyfill more than once, use @babel/polyfill/noConflict instead to bypass the warning.
```
warning.
=> Babel "polyfill loaded twice" warning fix

blocks/init/src/Blocks/custom/paragraph/components/paragraph-editor.js, scripts/editor/register-blocks.js
Fixes issue with Paragraph block not behaving corretly with regards to enter-block-splitting, merging blocks, etc.
It now behaves exactly like the native Paragraph block! 🎉 
Also, the `mergeableAttributes` functionality should work fine with prefixed attributes now (the solution is not the greatest, but with the data we get passed to the merge function that's the best I could do).
=> Paragraph fix

package.json
As we had `^2.2.0` in our `package.json`, the latest version of the config wasn't being pulled, so the (very) recently added semicolon rule wasn't applying. This PR bumps the version of the config to include the newest one.
=> Infinum ESLint config version bump

blocks/init/src/Blocks/variations/button-block/manifest.json, blocks/init/src/Blocks/variations/card-simple/manifest.json, scripts/storybook/helpers.js
Related to issue: #447 
Removes example key from manifest and updates blockDetails helper to fallback to attributes if example attributes are not defined
https://user-images.githubusercontent.com/23059501/140516910-6deb3652-1326-4bf2-bbfe-e6dff76ff2bb.mov
=> Remove example attributes. Adjust blockDetails helper

scripts/components/custom-select/custom-select.js, styles/override-editor.scss
Issue: [#426](https://github.com/infinum/eightshift-frontend-libs/issues/426)
Added z-index to `CustomSelect` component to prevent overlapping with other components.
=> Fix overlapping issue

blocks/init/src/Blocks/components/button/button.php, blocks/init/src/Blocks/components/button/components/button-options.js
This PR should fix #489. It adds a `TextControl` for the `buttonAriaLabel` attribute to `button-options.js` and changes `button.php` so that we only output the `aria-label` attribute if it's not empty.
=> Fix for #489: Buttons have an aria-label attribute, but no editor for it

scripts/components/collapsable-component-use-toggle/collapsable-component-use-toggle.js, scripts/components/index.js
This PR adds the missing export for the component 😅  and spits out content only when `showLabel` and `showUseToggle` are both `false`, allowing for more flexibility.
=> CollapsableComponentUseToggle fix and tweak

scripts/components/custom-select/custom-select.js
Looks like in some cases with async multiSelect values weren't picked up properly, this PR fixes it.
=> Custom select async multi-select setAttr fix

blocks/init/src/Blocks/components/lists/components/lists-editor.js, blocks/init/src/Blocks/components/lists/components/lists-options.js, blocks/init/src/Blocks/components/lists/lists.php, blocks/init/src/Blocks/components/lists/manifest.json
This PR:
* implements a way to change the value of the `listsOrdered` attribute from the editor
* implements additional checks that the `listsOrdered` attribute can be only `ul` or `ol`
* alternatively, we could make the `listsOrdered` attribute a boolean, but I decided for this approach to not break backwards compatibility - let me know if you think we should have a different approach
=> Lists component improvements

scripts/components/custom-select/custom-select.js, scripts/editor/fetch-wp-api.js, styles/override-editor.scss
Changes:
- fixed menu item overlap issue (closes #509)
- fixed issue with `getFetchWpApi` if called standalone
- tweaked menu design so it's connected to the select menu itself and has a bit of the content below peeking through (makes it easier to see if multiple elements are around)
After:
Before:
=> CustomSelect overlap fixes and fetchWpApi fix

blocks/init/src/Blocks/components/accordion/accordion.php, blocks/init/src/Blocks/components/button/button.php, blocks/init/src/Blocks/components/head/head.php, blocks/init/src/Blocks/components/head/manifest.json, blocks/init/src/Blocks/components/image/image.php, blocks/init/src/Blocks/components/modal/modal.php, blocks/init/src/Blocks/components/search-bar/search-bar.php
Decided to split this into two PRs, so it doesn't become too big. 😅 
Fixes these issues reported in #491:
=> A11y improvements: Part 1

blocks/init/src/Blocks/assets/scripts/application-blocks-editor.js, scripts/editor/register-blocks.js
Adds support for deprecating and migrating block attributes, based on https://developer.wordpress.org/block-editor/reference-guides/block-api/block-deprecation/.
Closes #291 .
(will be added to Docs soon)
It supports 2 ways of doing this, both should happen in `blockName-deprecations.js` (same level as `blockName-style.scss`, `blockName-block.js`, ...)
**The easy (and preferred) way is to have:**
```js
export const deprecated = [
{
oldAttributes: {
prevNextNavButtonsPrevUrl: {
type: "string"
},
prevNextNavButtonsNextUrl: {
type: "string"
},
},
newAttributes: ({ prevNextNavButtonsPrevUrl, prevNextNavButtonsNextUrl }) => ({
prevNextNavButtonsPrevUrl2: prevNextNavButtonsPrevUrl,
prevNextNavButtonsNextUrl2: prevNextNavButtonsNextUrl,
}),
},
];
```
in the file.
`oldAttributes` are the old …
=> Block attribute deprecation/migration

blocks/init/src/Blocks/assets/scripts/application-blocks-editor.js, scripts/editor/register-blocks.js
Added check if variation block has icon in it's manifest.
If it doesn't, script will import it's parent manifest and then it will set variation missing icon to parent block icon.
=> Add icon from the parent block to block variations if no icon is supplied

blocks/init/assets/scripts/application.js, blocks/init/src/Blocks/assets/scripts/application-blocks.js, scripts/components/advanced-color-picker/advanced-color-picker.js, scripts/components/advanced-color-picker/docs/story.js, scripts/components/alignment-toolbar/alignment-toolbar.js, scripts/components/collapsable-component-use-toggle/collapsable-component-use-toggle.js, scripts/components/color-picker-component/color-picker-component.js, scripts/components/custom-select/custom-select.js, scripts/components/heading-level/heading-level.js, scripts/components/icon-toggle/icon-toggle.js, scripts/components/link-edit-component/link-edit-component.js, scripts/components/link-toolbar-button/link-toolbar-button.js, scripts/components/option-picker/option-picker.js, scripts/components/simple-vertical-single-select/simple-vertical-single-select.js
- ColorPickerComponent doesn't show a label if not passed, so it can be used inline now
- ColorPickerComponent now shows tooltip (customizeable, has defaults) on the button if no label is passed
- CustomSelect can now be switched to compact mode (height reduced a bit) so it can nicely integrate with other options inline
- CustomSelect has a `style` property now (currenlty tweaks border color)
- most of the components can now be disabled through an attribute
For example, on more complext projects a (part of the) Paragraph options can be made more compact with the new CustomSelect styles.
\-
=> Component improvements

scripts/index.js
Changelog:
- add Advanced color picker to `scripts/index.js` that was causing a crash
=> Fix for advanced color picker

blocks/init/src/Blocks/components/drawer/assets/drawer.js, blocks/init/src/Blocks/components/drawer/drawer-style.scss, blocks/init/src/Blocks/components/drawer/drawer.php, blocks/init/src/Blocks/components/drawer/manifest.json, blocks/init/src/Blocks/components/hamburger/hamburger.php, blocks/init/src/Blocks/components/hamburger/manifest.json, blocks/init/src/Blocks/components/layout-three-columns/layout-three-columns.php, blocks/init/src/Blocks/components/layout-three-columns/manifest.json
This PR, [along with the one on infinum/eightshift-boilerplate](https://github.com/infinum/eightshift-frontend-libs/pull/540), fixes the accessibility issues reported in #534.
* `layout-three-columns` now supports setting an ARIA role for it
* `hamburger` now supports labels
* `drawer` has been refactored to improve accessibility and make the component simpler:
* page overlay and positioning support was removed, which fixes the interactive semantics issues with page overlays, and also IMO looks a bit cleaner
* drawers now use `display: none` to hide themselves, instead of visibility hacks, which fixes the tab order issues
The new drawer:
Tab order demo:
https://user-images.githubusercontent.com/1742806/149909699-38b292c6-b9fa-4da6-9c8c-7e475b85ef51.mov
=> Improve header / footer accessibility, fix #534

blocks/init/src/Blocks/components/accordion/accordion-style.scss, blocks/init/src/Blocks/components/accordion/accordion.php, blocks/init/src/Blocks/components/accordion/assets/accordion.js
Fixes some a11y issues with the accordion component:
* setting ARIA attributes using `Element` properties isn't supported in Firefox, so this was changed to `setAttribute`
* the accordion panel region didn't have the `aria-labelledby` attribute
* when clicking on the accordion, text would flash between black and white a bit because the hover state changed it to white, but the active state had `color: inherit;` set - which would inherit the color disregarding the hover state
=> Accordion A11y improvements

blocks/init/src/Blocks/components/button/manifest.json, blocks/init/src/Blocks/components/lists/manifest.json, blocks/init/src/Blocks/components/paragraph/manifest.json, blocks/init/src/Blocks/manifest.json
This PR changes the default color scheme so the contrast with white or black foregrounds is in line with WCAG AAA requirements (as they're mostly used as background colors for white or black text, mostly on buttons and as wrapper backgrounds).
As this is WCAG AAA compliant, lesser contrast (which will probably happen if the foreground colors aren't exactly `#fff` or `#000`) should still be AA-level compliant.
As project usually define their own color schemes, this PR will only affect the starter theme. As discussed previously with @iruzevic, these colors don't have brand meaning and were chosen arbitrarily, so these changes are mostly the same.
I'll work on a contrast warning later on.
This is what buttons now look like:
Relevant: https://webaim.org/resources/contrastchecker/
=> Change color scheme to match WCAG contrast requirements

styles/override-editor.scss
Fix a couple of warnings in build output for `override-editor.scss` regarding the `hsl()` function.
One warning is still present, but that's related to normalize package and we can only wait for the update.
Removed a lot of whitespace from empty lines.
=> Fix warnings on hsl function

blocks/init/src/Blocks/components/header/header-style.scss, blocks/init/src/Blocks/components/heading/heading-style.scss, blocks/init/src/Blocks/components/layout-three-columns/layout-three-columns-style.scss, blocks/init/src/Blocks/components/lists/lists-style.scss, blocks/init/src/Blocks/components/menu/styles/horizontal/menu-horizontal-style.scss, blocks/init/src/Blocks/components/menu/styles/vertical/menu-vertical-style.scss, blocks/init/src/Blocks/components/paragraph/paragraph-style.scss, blocks/init/src/Blocks/custom/featured-posts/components/featured-posts-options.js, blocks/init/src/Blocks/custom/featured-posts/manifest.json
This PR is focused on preventing overflows and clipping in regards to [WCAG AA SC 1. 4. 10.: Reflow](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html).
* Makes the number of items per row in the Featured Posts block a responsive attribute, which was previously a single value for all viewports.
* Stops the header component from overflowing by setting `min-height` instead of `height`
* Makes use of `flex-wrap` in `layout-three-columns` and `menu-horizontal` so it doesn't clip or overflow
Wrapping:
Responsive Featured posts:
https://user-images.githubusercontent.com/1742806/154236174-898535ae-6f24-41cf-b3fb-f30d0d14e283.mov
Non-overflowing content:
=> Improvements for small viewports

scripts/components/custom-select/custom-select.js, scripts/components/custom-select/docs/story.js, scripts/components/index.js, scripts/index.js
Because we don't have `react-select` exposed in our project, when trying to import certain react-select elements we get an error.
To work around that, there are new components that wrap around React-Select's elements:
- `CustomSelectCustomOption` -> `components.Option`
- `CustomSelectCustomValueDisplay` -> `components.SingleValue`
- `CustomSelectCustomMultipleValueDisplay` -> `components.MultiValueLabel`
- `CustomSelectCustomMultipleValueDisplayContainer` -> `components.MultiValueContainer`
- `CustomSelectCustomMultipleValueRemoveButton` -> `components.MultiValueRemove`
Also, there are new customizations available for multi-selects! (see screenshot), three new props are available in CustomSelect for that:
- `customMultiValueDisplayComponent`
- `customMultiValueDisplayContainerComponent`
- …
=> Custom select custom component wrappers

blocks/init/src/Blocks/custom/carousel/assets/carousel-slider.js, blocks/init/src/Blocks/custom/carousel/carousel.php
This PR:
* adds an ARIA label to the carousel navigation arrows
* enables the Swiper A11y module, which provides decent ARIA semantics for Swiper-rendered DOM elements
* this is set to their default configuration, which seems sensible enough for everything apart from the `slideRole`, which I've explicitly overridden to `figure` for semantic correctness, and because we don't have a nice way to set labels for the default `group` roles on slide containers
=> Carousel A11y improvements

setup/create-wp-project/src/search-replace.js
This PR separates conditions checking existence of `projectName` and `description` attributes when `search-replace.js` runs under `create-wp-project`.  
This will fix #570 and replace the theme/plugin name placeholders if the description isn't set and vice versa.
=> Separate conditions for projectName and description in create-wp-project

blocks/init/src/Blocks/custom/featured-categories/featured-categories-style.scss, blocks/init/src/Blocks/custom/featured-categories/featured-categories.php, blocks/init/src/Blocks/custom/featured-posts/featured-posts-style.scss, blocks/init/src/Blocks/custom/featured-posts/featured-posts.php
This PR changes markup for card groups in `featured-posts` and `featured-categories` to unordered lists instead of `div`s for a better screen reader experience and improved semantics. It also adds CSS resets for lists to those blocks, so no visual changes occur.
See https://inclusive-components.design/cards/ for more information about this choice.
=> A11y: Use list markup for card groups

blocks/init/src/Blocks/components/heading/heading.php, blocks/init/src/Blocks/components/paragraph/paragraph.php
This PR:
* makes sure we render headings and paragraphs only if they have content
* moves `outputCssVariables` call to be outside `<h_>` and `<p>` tags (i.e. renders the `<style>` tag in heading/paragraph's parent node)
* this is a large a11y improvement, as  `<style>` tag contents in an `<h_>` tag are for some reason read out by VoiceOver and included in Rotor navigation. imagine hearing `.heading[data-id='09d71c93caf0cd36f8713560cde6ef26'] {` instead of an actual heading
=> A11y: Small improvements to heading and paragraph components

styles/override-editor.scss
Closes #581.
For some reason when scrollbars are enabled in Firefox and Safari the options panel was overflowing the Gutenberg sidebar element.
`scrollbar-gutter: stable` ([if you wanna learn more](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter)) fixes the problem in Firefox and the sidebar now looks proper, without any overflow.
Unfortunately, Safari doesn't support `scrollbar-gutter` (yet), so I had to resort to simple `overflow-x: hidden`, which means that on the right instead of the empty space there's a scrollbar, but nothing is clipped by it (and there is no more horizontal scroll).
\-
\-
=> Fix for option overflow when scrollbars are enabled

blocks/init/src/Blocks/components/hamburger/hamburger.php
Fixes the hamburgerLabel conditional to work as expected, i.e. output `__('Menu', 'eightshift-frontend-libs')` when attribute is undefined. Sorry 😶‍🌫️ 
Also removes the `aria-label`, as `label` is sufficient.
=> Fix hamburger label conditional

scripts/helpers/text-helpers.js, tests/unit/scripts/helpers/text-helpers.test.js
Closes #422.
Helper is now (a bit) smarter about the passed separator length. Also now throws an `Error` if separator length would occlude the truncate string completely.
\-
\-
=> Text helpers fixes and tests

setup/create-wp-project/src/commands/theme.js, setup/create-wp-project/src/replace-version-numbers.js
Closes #550.
As per the issue, in these files:
- `style.css`
- `functions.php`
- `package-lock.json`
- `package.json`
the version is set to '1.0.0' instead of whatever was pulled from boilerplate.
Also, `CHANGELOG.md` now gets replaced with a blank template.
\-
\-
=> Clean changelog and versions that start from 1.0.0

blocks/init/src/Blocks/components/accordion/accordion.php, blocks/init/src/Blocks/components/jumbotron/jumbotron.php, blocks/init/src/Blocks/components/lists/components/lists-options.js, blocks/init/src/Blocks/components/menu/styles/horizontal/menu-horizontal-style.scss, blocks/init/src/Blocks/components/menu/styles/vertical/menu-vertical-style.scss, blocks/init/src/Blocks/components/video/components/video-options.js, blocks/init/src/Blocks/components/video/video.php
This PR:
* changes the accordion icon's containing element from `div` to `span`, as `div` is not an allowed child of `button`
* adds `role="section"` to jumbotron container
* replaces SimpleVerticalSingleSelect with SimpleHorizontalSingleSelect in list component's options, a misconfiguration of which caused the list order attribute change to fail 🙈 
* adds CSS to distinguish menu links from other text on the page using underlines
* see screenshots below
* includes `prefers-contrast` rules
* this simply extends the current menu styles, but we should consider rewriting the menu component to be more in line with current practices and new development kit versions
* warns users that it may be a bad idea to set a video as autoplaying, with sound, and without controls
* actually renders …
=> A11y improvements after a11y review

blocks/init/src/Blocks/components/jumbotron/jumbotron.php
In my previous PR, I added `role="section"` to the Jumbotron container, which is an abstract role and the HTML Living Standard considers it incorrect. I've replaced it with `role="region"` in this PR. Sorry.
=> Replace role="section" with role="region"

scripts/components/color-picker-component/color-picker-component.js
Because `SCRIPT_DEBUG == true` + Gutenberg = 💥  (in general, but also with `ColorPickerComponent`), this PR works around the "object is not extendable" error.
\-
\-
=> Fix WP SCRIPT_DEBUG strict mode quirk with ColorPickerComponent

blocks/init/src/Blocks/components/hamburger/hamburger-style.scss
Fix a bug in Safari which causes a glitch in hamburger from default to active state (`is-menu-open`) animation.
This is how it looks like in Safari and iOS without the fix:
https://user-images.githubusercontent.com/22823970/169843183-a9275d77-5996-48e1-9fff-9828c43605eb.mov
=> Fix a bug in Safari for hamburger animations

blocks/init/assets/styles/parts/utils/_shared-variables.scss
Added variable $media-breakpoints to _shared-variables.scss
$media-breakpoints is defined in node_modules>media-blender with !default keyword which means if there is no variable defined, use these values.
I had to reassign that variable in eightshift-frontend-libs and pull data from blocks manifest.json with global-settings function.
=> Adds media-breakpoints variable that pulls variables from global manifest.json

blocks/init/src/Blocks/assets/styles/application-blocks-editor.scss, blocks/init/src/Blocks/assets/styles/application-blocks-frontend.scss, blocks/init/src/Blocks/assets/styles/application-blocks.scss, styles/index.scss
Changes:
- "normalize" import is not in the main import to prevent normalize "leaking" into the admin
- added all changes from the develop branch
\-
\-
=> Webpack 5 - seperate Normalize import from main index.scss

blocks/init/src/Blocks/custom/carousel/carousel.php
The carousel template file had an escaped string, which makes no sense to have. It's a string, so it needs no escaping or echoing using PHP.
=> Remove unnecessary escaping in carousel template file

webpack/helpers.js
If the value in global manifest contained a comma, the build would error out because the commas output in SASS maps would confuse it. Though, if you add `''` or `()` around your value the CSS variable output wouldn't be right.
This PR fixes this by adding `()` around the value (just in SASS) if it's a string value and contains a comma.
\-
\-
=> SASS map output fix if comma in value

styles/override-editor.scss
Changed styles of appender button in Gutenberg editor when button is not the only child in component, now button is centered instead of full length.
=> Fix appender button styles when it's not the only child

composer.json, scripts/components/advanced-color-picker/advanced-color-picker.js
Fixed the double import of `@wordpress/components` statement in the advanced color picker component
=> Fix double import

blocks/init/src/Blocks/assets/styles/application-blocks-editor.scss, blocks/init/src/Blocks/assets/styles/application-blocks-frontend.scss, blocks/init/src/Blocks/assets/styles/application-blocks.scss
Removed import of normalize stylesheet from applicationBlocksFrontned and applicationBlocksEditor stylesheets since it was already imported in applicationBlocks.
Changed the order of the import and moved the normalize script as first.
Multiple imports of normalize script were overriding the font-family declaration in the theme.
=> Update imports of normalize stylesheet

blocks/init/src/Blocks/components/lists/lists.php
Variable for "list type options" and "lists type" have the same name causing premature return.
Updated the variable name for viable lists options to differentiate from the list type variable name.
=> Fix Lists component : identical variable names

blocks/init/src/Blocks/components/button/button.php
As it is currently implemented, the escaped value for the button attributes would break the `title` attribute of the button component.
For instance, if the content of the button had multiple words, like
```
Back to the home page
```
the attribute would be rendered as
```html
<button class="btn" title="Back" to="" the="" home="" page="" data-id="35459615a50e5e94f67bcc626250b58f" href="https://example.test/">
<i class="icon btn__icon" data-id="5f6e3cc5c768d537cbfac74637bd08f6">
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M14.283 5 21 12l-6.717 7" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none"></path><path stroke="currentColor" stroke-width="2" stroke-linecap="round" d="M19.733 …
```
=> Fix the button attribute value concatenation

blocks/init/src/Blocks/wrapper/components/wrapper-editor.js, blocks/init/src/Blocks/wrapper/components/wrapper-options.js, blocks/init/src/Blocks/wrapper/manifest.json, blocks/init/src/Blocks/wrapper/wrapper.php
Closes #732.
- adds an option to select wrapper HTML tag. Defaults to `<div>`. Other options include `<section>`, `<aside>`, `<article>`
- available on `Spacing Only` and `Spacing & Layout`
Currently doesn't work on `Column` block. Do we need this option there as well?
If you have any questions or suggestions, let me know.
**Options**
**Wrapper with `<article>` tag**
=> Add option to select wrapper HTML tag

blocks/init/src/Blocks/custom/columns/manifest.json, scripts/components/custom-slider/shared.js, styles/override-editor.scss, styles/wp-version-specific/_wp-6-4.scss
Changes:
- added WP 6.4 style overrides
- fixed Columns default presets
- fixed RangeSlider ColumnPicker variant click and drag
Closes #763
=> WP 6.4 fixes

CHANGELOG.md, package.json
Moves `@babel/preset-react` to dependencies (from devDependencies)
=> Frontend libs 9.3.1

CHANGELOG.md, package.json
Same as #806, just for main branch
=> FE libs 9.6.0 - Git untagling pt2

blocks/init/src/Blocks/wrapper/manifest.json, blocks/init/src/Blocks/wrapper/wrapper.php
Fixes using $this out of object context when we wan to render wrapper as a standalone component.
https://github.com/infinum/eightshift-frontend-libs/issues/814
=> Fix Wrapper as standalone component

blocks/init/src/Blocks/components/quote/quote.php
Each element within the quote block is read individually.
https://github.com/infinum/eightshift-frontend-libs/assets/97440314/2234e838-44e9-49f0-88af-870bbb46400c
https://github.com/infinum/eightshift-frontend-libs/assets/97440314/1260c1d9-98dc-4cbb-81af-c4f8251edd89
https://app.productive.io/1-infinum/tasks/7863543
=> Standardize Accessibility of Quote Blocks Across Browsers

scripts/helpers/cookies.js
Adds an optional `domain` argument to the setCookie helper so the cookie domain can be set.
Additionally, does a minor restructuring of how the `document.cookie` value is generated.
=> Support an optional `domain` argument in setCookie helper

CHANGELOG.md, package.json, scripts/editor/registration.js
- `supports` key to the blocks registration process.
=> Adding supports to block registration

scripts/helpers/cookies.js
We started getting errors from BugSnag for unsecured cookies, so I solved this on a project, but consider we should also have this as an option in FE Libs cookie helper.
This will set `sameSite` default to `Lax` (which is already default, but not in all browsers, like Safari or Firefox). Means that cookie is not sent on cross-site requests by default. More [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#lax).
Also, set `Secure` attribute by default, which indicates that the cookie is sent to the server only when a request is made with the https: scheme (except on localhost), and therefore, is more resistant to [man-in-the-middle](https://developer.mozilla.org/en-US/docs/Glossary/MitM) attacks.
=> Add Secure and SameSite parameters as options to cookie method
